#!/bin/sh
set -xe

action=${CNAB_ACTION:-install}
name=${CNAB_INSTALLATION_NAME:-rancher-cloud}

helm_timeout=20m

rancher_billing_adapter_image_arguments=
if [[ ! -z "${RANCHER_BILLING_ADAPTER_IMAGE}" ]]
then
        rancher_billing_adapter_image_arguments="--set rancherBillingAdapterImage=${RANCHER_BILLING_ADAPTER_IMAGE}"
fi
if [[ ! -z "${RANCHER_BILLING_ADAPTER_IMAGE_DIGEST}" ]]
then
        rancher_billing_adapter_image_arguments="${rancher_billing_adapter_image_arguments} --set rancherBillingAdapterImageDigest=${RANCHER_BILLING_ADAPTER_IMAGE_DIGEST}"
else
	rancher_billing_adapter_image_arguments="${rancher_billing_adapter_image_arguments} --set rancherBillingAdapterImageTag=${RANCHER_BILLING_ADAPTER_IMAGE_TAG}"
fi

azure_billing_arguments=
if [[ ! -z "${AZURE_CLIENT_ID}" ]]
then
	azure_billing_arguments="--set global.azure.enabled=true --set global.azure.identity.clientId=${AZURE_CLIENT_ID} --set global.azure.extension.resourceId=${AZURE_RESOURCE_ID} --set global.azure.marketplace.planId=${AZURE_PLAN_ID}"
fi

case $action in
    install)
        echo "Installing Rancher CSP Billing Adapter"
        helm upgrade --install rancher-csp-billing-adapter /cnab/app/charts ${rancher_billing_adapter_image_arguments} ${azure_billing_arguments} --namespace cattle-csp-billing-adapter-system --create-namespace --atomic --timeout ${helm_timeout}
        echo "Rancher CSP Billing Adapter successfully installed"
        ;;
    uninstall)
        echo "Uninstalling Rancher CSP Billing Adapter"
        helm uninstall rancher-csp-billing-adapter -n cattle-csp-billing-adapter-system --timeout ${helm_timeout}
        echo "Rancher CSP Billing Adapter successfully uninstalled"
        ;;
    upgrade)
        echo "Upgrade action"
        ;;
    status)
        echo "Status action"
        ;;
    *)
    echo "No action for $action"
    ;;
esac
echo "Action $action complete for $name"
