# Default values for rancher-cloud.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  aws:
    enabled: false
    accountNumber: ""
    roleName: ""
  google:
    enabled: false
    ubbagent:
      reportingSecretName: fake-reporting-secret
      image:
        repository: gcr.io/cloud-marketplace-tools/metering/ubbagent
        tag: latest

  csp:
    images:
      rancher_cloud:
        registry: registry.suse.de/suse/sle-15-sp5/update/pubclouds/images
        image: rancher-deployer
        tag: latest
      csp_rancher_usage_operator:
        registry: registry.suse.de/suse/sle-15-sp5/update/pubclouds/images
        image: rancher-usage-operator
        tag: latest
      rancher_csp_billing_adapter:
        registry: registry.suse.de/suse/sle-15-sp5/update/pubclouds/images
        image: rancher-billing-azure-by-suse-ltd
        tag: latest

# NOTE: the rancher-cloud image can also be specified in the CSP-specific
# sections, namely global.azure.images or global.csp.images. If any of the
# CSP-specifics sections are present and enabled, the rancher-cloud image
# in those sections have precedent over the image specified in the image
# section here.
image:
  repository: registry.suse.de/suse/sle-15-sp5/update/pubclouds/images/rancher-deployer
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"


imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

securityContext:
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  runAsUser: 0

certManagerChartVersion: v1.12.3
rancherChartVersion: 2.7.11
rancherHostname: csp-billing
rancherServerURL: https://csp-billing
rancherReplicas: 1
rancherBootstrapPassword: Ranch99
rancherIngressClassName: none
