apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "rancher-cloud.fullname" . }}
  labels:
    {{- include "rancher-cloud.labels" . | nindent 4 }}
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 0
  ttlSecondsAfterFinished: 60
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "rancher-cloud.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ template "rancher-cloud.fullname" . }}
      restartPolicy: Never
      containers:
        - name: {{ template "rancher-cloud.name" . }}
          image: {{ template "rancher-cloud.image" . }}
          imagePullPolicy: "{{ .Values.image.imagePullPolicy }}"
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          command:
            - /cnab/app/run
          env:
            - name: CNAB_ACTION
              value: "install"
{{- if and (.Values.global) (.Values.global.aws) (.Values.global.aws.enabled) }}
            - name: AWS_ACCOUNT_NUMBER
              value: "{{ .Values.global.aws.accountNumber }}"
            - name: AWS_ROLE_NAME
              value: "{{ .Values.global.aws.roleName }}"
{{- end }}
{{- if and (.Values.global) (.Values.global.azure) (.Values.global.azure.enabled) }}
            - name: AZURE_CLIENT_ID
              value: "{{ .Values.global.azure.identity.clientId }}"
            - name: AZURE_RESOURCE_ID
              value: "{{ .Values.global.azure.extension.resourceId }}"
            - name: AZURE_PLAN_ID
              value: "{{ .Values.global.azure.marketplace.planId }}"
            - name: RANCHER_IMAGE_TAG
              value: {{ .Values.rancherImageTag | quote }}
            - name: RANCHER_USAGE_OPERATOR_IMAGE
              value: "{{ .Values.global.azure.images.csp_rancher_usage_operator.registry }}/{{ .Values.global.azure.images.csp_rancher_usage_operator.image }}"
            - name: RANCHER_USAGE_OPERATOR_IMAGE_DIGEST
              value: {{ .Values.global.azure.images.csp_rancher_usage_operator.digest | quote }}
            - name: RANCHER_BILLING_ADAPTER_IMAGE
              value: "{{ .Values.global.azure.images.rancher_csp_billing_adapter.registry }}/{{ .Values.global.azure.images.rancher_csp_billing_adapter.image }}"
            - name: RANCHER_BILLING_ADAPTER_IMAGE_DIGEST
              value: {{ .Values.global.azure.images.rancher_csp_billing_adapter.digest | quote }}
{{- else if and (.Values.global) (.Values.global.csp) (.Values.global.csp.images) }}
            {{- if .Values.global.csp.images.csp_rancher_usage_operator.digest }}
            - name: RANCHER_USAGE_OPERATOR_IMAGE_DIGEST
              value: {{ .Values.global.csp.images.csp_rancher_usage_operator.digest | quote }}
            {{- else }}
            - name: RANCHER_USAGE_OPERATOR_IMAGE_TAG
              value: {{ .Values.global.csp.images.csp_rancher_usage_operator.tag | quote }}
            {{- end }}
            - name: RANCHER_BILLING_ADAPTER_IMAGE
              value: "{{ .Values.global.csp.images.rancher_csp_billing_adapter.registry }}/{{ .Values.global.csp.images.rancher_csp_billing_adapter.image }}"
            {{- if .Values.global.csp.images.rancher_csp_billing_adapter.digest }}
            - name: RANCHER_BILLING_ADAPTER_IMAGE_DIGEST
              value: {{ .Values.global.csp.images.rancher_csp_billing_adapter.digest | quote }}
            {{- else }}
            - name: RANCHER_BILLING_ADAPTER_IMAGE_TAG
              value: {{ .Values.global.csp.images.rancher_csp_billing_adapter.tag | quote }}
            {{- end }}
{{- end }}
{{- if .Values.rancherHostname }}
            - name: RANCHER_HOSTNAME
              value: {{ .Values.rancherHostname | quote }}
{{- end }}
{{- if .Values.rancherServerURL }}
            - name: RANCHER_SERVER_URL
              value: {{ .Values.rancherServerURL | quote }}
{{- end }}
{{- if .Values.rancherReplicas }}
            - name: RANCHER_REPLICAS
              value: {{ .Values.rancherReplicas | quote }}
{{- end }}
{{- if .Values.rancherBootstrapPassword }}
            - name: RANCHER_BOOTSTRAP_PASSWORD
              value: {{ .Values.rancherBootstrapPassword | quote }}
{{- end }}
{{- if .Values.rancherIngressClassName }}
            - name: RANCHER_INGRESS_CLASS_NAME
              value: {{ .Values.rancherIngressClassName | quote }}
{{- end }}
            - name: RANCHER_CHART_VERSION
              value: {{ .Values.rancherChartVersion | quote }}
            - name: CERT_MANAGER_CHART_VERSION
              value: {{ .Values.certManagerChartVersion | quote }}
