apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "rancher-cloud.fullname" . }}-post-delete
  labels:
    {{- include "rancher-cloud.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "3"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: 3
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "rancher-cloud.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ template "rancher-cloud.fullname" . }}-post-delete
      restartPolicy: OnFailure
      containers:
        - name: {{ template "rancher-cloud.name" . }}
          image: {{ template "rancher-cloud.image" . }}
          imagePullPolicy: "{{ .Values.image.imagePullPolicy }}"
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          command:
            - /cnab/app/run
          env:
            - name: CNAB_ACTION
              value: "uninstall"
